site_name: Diseño de una red
theme: mkdocs
docs_dir: 'md'
site_dir: 'docs'
nav:
    - Home: index.md
    - Tema 3:
      - Capa Física: caracteristicas.md
      - Medios de transmision: Cableado.md
      - Cableado estructurado: cableado_estructurado.md
