site_name: Diseño de una red
theme:
  name: material
  language: es
  icon:
    repo: 'fontawesome/brands/github'
  features:
    - navigation.tabs
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - navigation.footer
    - toc.integrate
    - palette.toggle   

  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Modo oscuro
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Modo claro

plugins:
  - search
  - with-pdf
  - pdf-export:
      combined: true
#  - mkdocs-pdf-export-plugin 
     

markdown_extensions:
  - admonition
  - pymdownx.details           
  - pymdownx.highlight:
      linenums: true            
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
  - pymdownx.tabbed
  - pymdownx.tasklist
docs_dir: 'md'
site_dir: 'docs'
nav:
  - Inicio: index.md
  - Teoría:
      - Capa Física: caracteristicas.md
      - Medios de transmision: Cableado.md
      - Cableado estructurado: cableado_estructurado.md
  - Caso práctico: caso_practico.md