site_name: Diseño de una red
theme: material
palette:
      scheme: default
      toggle:
          icon: material/brightness-7 
          name: Canvia a mode oscur

      scheme: slate
      toggle:
          icon: material/brightness-4
          name: Canvia a mode clar
extra_css:
  - css/styles.css
markdown_extensions:
  - admonition
  - pymdownx.details
plugins:
    - search
    - pdf-export
    - page-to-pdf
docs_dir: 'md'
site_dir: 'docs'
nav:
    - Home: index.md
    - Tema 3:
      - Capa Física: caracteristicas.md
      - Medios de transmision: Cableado.md
      - Cableado estructurado: cableado_estructurado.md
      - Caso practico: caso_practico.md
